### ISSUE TITLE
Exploding gas cans

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1058] opened 2022-08-20 03:32 UTC
Gas cans / biofuel should explode when shot.

**Comment by QuentinGruber** [comment] 2022-08-20 07:45
Kinda a duplicate of #979

**Comment by Z1Meme** [comment] 2022-08-22 00:23
That's an entirely separate feature and should be removed from that issue
then.

**Comment by sofresh007** [comment] 2022-09-16 15:49
@avcio9  got this working on his branch already

**Closed** 2022-09-22 09:10 UTC
Labels: enhancement
