### ISSUE TITLE
Sometimes characters in multiplayer are missing all equipment

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#771] opened 2022-03-29 00:25 UTC
May be related to the "Logging out in vehicle breaks it" #770 issue, steps to reproduce unknown.

**Comment by QuentinGruber** [comment] 2022-05-26 18:34
Since #770 is fixed maybe this issue should be closed too as a wontfix ? Like we don't even know how to reproduce this.

**Closed** 2022-06-01 01:01 UTC
Labels: bug
